apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}"
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}

        env:
        - name: APP_MESSAGE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.secretName }}
              key: APP_MESSAGE

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5