apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-allow-frontend

spec:
  podSelector:
    matchLabels:
      app: backend

  policyTypes:
  - Ingress

  ingress:
  # ✅ Allow traffic from frontend pods
  - from:
    - podSelector:
        matchLabels:
          app: frontend