apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-allow-frontend

spec:
  podSelector:
    matchLabels:
      app: backend

  policyTypes:
    - Ingress
    - Egress   # ✅ IMPORTANT FIX

  ingress:
    - {}       # ✅ allow all incoming

  egress:
    - {}       # ✅ allow all outgoing