backend:
  replicas: 2   # ✅ keep 1 (your cluster is small)
  image: selvakumardocker/backend:latest

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

frontend:
  replicas: 2
  image: selvakumardocker/frontend:latest

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"
``