backend:
  image: selvakumardocker/backend:v27
  replicas: 1   # ✅ FIX (VERY IMPORTANT)

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

frontend:
  image: selvakumardocker/frontend:v25
  replicas: 1   # ✅ FIX

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"